spring:
    application:
        name: product-microservice
    datasource:
        url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
        username: root
        password: toor
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    cloud:
        loadbalancer:
          retry:
              enabled: true

server:
    port: 8081

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: "*"

    endpoint:
        health:
            show-details: always

    prometheus:
        metrics:
            export:
                enabled: true # Redundant, as the default value is already true

resilience4j:
    retry:
        instances:
            myRetry:
                max-attempts: 1
                waitDuration: 100ms
    ratelimiter:
        instances:
            myRateLimiter:
                limit-for-period: 1
                limit-refresh-period: 1s
                timeout-duration: 100ms
    circuitbreaker:
        instances:
            productService:
                registerHealthIndicator: true
                slidingWindowSize: 2
                failureRateThreshold: 50
                waitDurationInOpenState: 1s
                permittedNumberOfCallsInHalfOpenState: 1
                minimumNumberOfCalls: 2
                eventConsumerBufferSize: 10
    # circuitbreaker:
    #     instances:
    #         productService:
    #             registerHealthIndicator: true
    #             slidingWindowSize: 100
    #             permittedNumberOfCallsInHalfOpenState: 10
    #             minimumNumberOfCalls: 10
    #             waitDurationInOpenState: 10000
    #             failureRateThreshold: 50
    #             eventConsumerBufferSize: 10