spring:
    application:
        name: product-service
    datasource:
        url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
        username: root
        password: toor
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect

server:
    port: 8081

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: info,health,prometheus
    endpoint:
        info:
            enabled: true

    metrics:
        export:
            prometheus:
                enabled: true

resilience4j:
    retry:
        instances:
            myRetry:
                max-attempts: 3
                waitDuration: 500ms
    ratelimiter:
        instances:
            myRateLimiter:
                limit-for-period: 5
                limit-refresh-period: 1s
                timeout-duration: 500ms
    circuitbreaker:
        instances:
            productService:
                registerHealthIndicator: true
                slidingWindowSize: 100
                permittedNumberOfCallsInHalfOpenState: 10
                minimumNumberOfCalls: 10
                waitDurationInOpenState: 10000
                failureRateThreshold: 50
                eventConsumerBufferSize: 10