spring:
    application:
        name: gateway-service
    
    cloud:
        gateway:
            routes:
                -   id: product-microservice
                    uri: lb://product-microservice
                    predicates:
                        - Path=/products/**
                -   id: user-microservice
                    uri: lb://user-microservice
                    predicates:
                        - Path=/users/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true